#!/bin/bash

for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
do
cd /Volumes/Elements/OCF/sub${i}/PreCond
rm -rfv uras*.*

cd /Volumes/Elements/OCF/sub${i}/Cond
rm -rfv uras*.*

cd /Volumes/Elements/OCF/sub${i}/PostCond
rm -rfv uras*.*

done




